'kaiju': '/scratch/alvanuffelen/hackaton/DATABASES/kaiju_cleaned/proteins.fmi'
'kraken2': '/scratch/alvanuffelen/hackaton/DATABASES/kraken2_db_v2'
'bracken': '/scratch/alvanuffelen/hackaton/DATABASES/kraken2_db_v2'
'taxonomy': '/scratch/alvanuffelen/hackaton/DATABASES/taxonomy_20230719'
'kma': '/scratch/alvanuffelen/hackaton/DATABASES/kma_v3/kma_db'
'metaphlan': '/scratch/alvanuffelen/hackaton/DATABASES/metaphlan'
'centrifuge': '/scratch/alvanuffelen/hackaton/DATABASES/centrifuge_v3/centrifuge_db'
'mmseqs2': '/scratch/alvanuffelen/hackaton/DATABASES/mmseqs2_lca_cleaned/nr_lca_cleanedDB'
'motus': '/scratch/alvanuffelen/hackaton/DATABASES/motus'